# Site settings
## Change the values as needed.
title: Bitwiser-Material
email: brijeshb42@gmail.com
description: "A jekyll theme implementing material design by using muicss."
keywords: "jekyll, theme, material, muicss"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: brijeshb42
  twitter: brijeshb42
  email: brijeshb42@gmail.com
  github: brijeshb42/bitwiser-material/
exclude:
  - bower_components
  - README.md
full_name: Brijesh

##set this to enable disqus commenting
disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
